### ISSUE TITLE
Direct Mode not works / 直连模式无法使用

### ISSUE THREAD

**Issue by tao1991123** [nacos-group/nacos-sdk-nodejs#15]
复制 Readme里面的代码,
```javascript
// index.js

const {NacosConfigClient} = require('nacos'); // js

// for direct mode
const configClient = new NacosConfigClient({
  serverAddr: '127.0.0.1:8848',
});

// listen data changed
configClient.subscribe({
  dataId: 'test',
  group: 'DEFAULT_GROUP',
}, content => {
  console.log(content);
});
```

执行 `node index.js` 然后报错
```bash
[Sun Mar 31 2019 00:20:06 GMT+0800 (GMT+08:00)][pid: 56608][NacosConfigClient] AssertionError [ERR_ASSERTION]: [Client] options.endpoint is required
Error Stack:
  AssertionError [ERR_ASSERTION]: [Client] options.endpoint is required
    at new DataClient (/Users/xxx/code/demo/node_modules/nacos-config/dist/client.js:31:9)
    at Object.createRealClient (/Users/xxx/code/demo/node_modules/cluster-client/lib/index.js:102:22)
    at new Leader (/Users/xxx/code/demo/node_modules/cluster-client/lib/leader.js:38:37)
    at ClusterClient.[ClusterClient#init] (/Users/xxx/code/demo/node_modules/cluster-client/lib/client.js:88:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Error Additions:
  generatedMessage: false
  code: "ERR_ASSERTION"
  actual: undefined
  expected: true
  operator: "=="
```

**Comment by czy88840616** [comment]
已修复，再试试。

**Comment by tao1991123** [comment]
done
