### ISSUE TITLE
NacosConfigClient TCP timeout

### ISSUE THREAD

**Issue by liyinkan** [nacos-group/nacos-sdk-nodejs#43]
Nacos version: 1.1.4
nacos-nodejs-sdk version: 2.0.0
Nodejs version: 14.15.5
npm version: 6.14.11
OS version: centos 7.6

```
logger.info('Connecting Nacos config client...')
const configClient = new NacosConfigClient({
    serverAddr: config.nacos.serverAddr,
    namespace: config.nacos.namespace
});
const content = await configClient.getConfig('-', '-');

// let doc = yaml.load(content)
let doc = JSON.parse(content)
appConfig.set(doc)
```

output:

```
2021-02-23 18:28:39,119 WARN 2197 nodejs.ResponseTimeoutError: register to channel: DiamondClient@undefined failed, will retry after 3s, Server no response in 3000ms, address#127.0.0.1:7777
    at Timeout._onTimeout (/app/data/${project}/node_modules/tcp-base/lib/base.js:225:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
socketMeta: {"id":2,"dataLength":91,"bufferSize1":0,"bufferSize2":0,"startTime":1614076116118,"endTime":1614076116118,"writeSuccess":true}
name: "ResponseTimeoutError"
pid: 2197
```

I tried curl command on server
```
curl -G -d 'tenant=${namespace}' -d 'dataId=${dataid}' -d 'group=${group}' http:/${host}/nacos/v1/cs/configs
```
which returns the correct configuration stored in nacos.

In addition, the same code works in win10 and Java client with same configuration can get nacos config successfully.

**Comment by KomachiSion** [comment]
超时问题请自查网络环境
