### ISSUE TITLE
启动报错了，，本地可以运行，部署到linux服务器就出错了

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [nacos-group/nacos-sdk-nodejs#58]
(node:15631) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token C in JSON at position 2 (address: 127.0.0.1:7777)
    at JSON.parse (<anonymous>)
    at Function.decode (/root/works/eryipay/node_modules/nacos-config/node_modules/cluster-client/lib/protocol/packet.js:86:26)
    at Follower.decode (/root/works/eryipay/node_modules/nacos-config/node_modules/cluster-client/lib/follower.js:68:27)
    at Follower._readPacket (/root/works/eryipay/node_modules/tcp-base/lib/base.js:308:25)
    at Follower._handleReadable (/root/works/eryipay/node_modules/tcp-base/lib/base.js:374:26)
    at Socket.socket.on (/root/works/eryipay/node_modules/tcp-base/lib/base.js:392:40)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at onEofChunk (_stream_readable.js:512:7)
    at readableAddChunk (_stream_readable.js:232:5)
(node:15631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:15631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C

**Comment by KomachiSion** [comment]
明显是服务端返回的内容有问题，自行排查是否有接入nginx/vpn等可能代理回复数据的组件。或者通过网络抓包来查看回包内容
