### ISSUE TITLE
在项目中使用nacos-sdk-nodejs后，服务一段时间后会挂掉

### ISSUE THREAD

**Issue by kingchary** [nacos-group/nacos-sdk-nodejs#90]
各位大神，你们好。

我遇到个奇怪的问题，服务会突然断掉。
奇怪的是自己电脑没问题，但有两台测试服务器就出现这个问题。ping和crul nacos服务都正常。

代码截图
![image](https://user-images.githubusercontent.com/1967972/171005404-73293df2-467d-4565-ae27-a0856f0035f0.png)

启动日志
2022-05-30 21:39:51,286 WARN 112165 nodejs.ResponseTimeoutError: register to channel: DiamondClient@undefined failed, will retry after 3s, Server no response in 3000ms, address#127.0.0.1:7777
    at Timeout._onTimeout (/www/wwwroot/test/node_modules/tcp-base/lib/base.js:225:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
socketMeta: {"id":2,"dataLength":91,"bufferSize1":0,"bufferSize2":0,"startTime":1653917988281,"endTime":1653917988282,"writeSuccess":true}
name: "ResponseTimeoutError"
pid: 112165
hostname: localhost.localdomain

2022-05-30 21:39:57,292 WARN 112165 nodejs.ResponseTimeoutError: register to channel: DiamondClient@undefined failed, will retry after 3s, Server no response in 3000ms, address#127.0.0.1:7777
    at Timeout._onTimeout (/www/wwwroot/test/node_modules/tcp-base/lib/base.js:225:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
socketMeta: {"id":3,"dataLength":91,"bufferSize1":0,"bufferSize2":0,"startTime":1653917994291,"endTime":1653917994291,"writeSuccess":true}
name: "ResponseTimeoutError"
pid: 112165
hostname: localhost.localdomain

2022-05-30 21:40:03,299 WARN 112165 nodejs.ResponseTimeoutError: register to channel: DiamondClient@undefined failed, will retry after 3s, Server no response in 3000ms, address#127.0.0.1:7777
    at Timeout._onTimeout (/www/wwwroot/test/node_modules/tcp-base/lib/base.js:225:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
socketMeta: {"id":4,"dataLength":91,"bufferSize1":0,"bufferSize2":0,"startTime":1653918000296,"endTime":1653918000296,"writeSuccess":true}
name: "ResponseTimeoutError"
pid: 112165
hostname: localhost.localdomain

**Comment by wmvm0** [comment]
解决了吗，我也遇到这个问题了

**Comment by helloyxw** [comment]
我也遇到过这个问题，最后发现node项目停止时 端口号没有释放，把端口号释放了，问题就消失了。

**Comment by liucong1** [comment]
问题到现在还存在……

**Comment by suzhelan** [comment]
我也遇到了这样的问题

**Comment by KomachiSion** [comment]
> 我也遇到过这个问题，最后发现node项目停止时 端口号没有释放，把端口号释放了，问题就消失了。

看起来似乎不是node-sdk的问题， 而是node项目本身的问题？

**Comment by KomachiSion** [comment]
通过AI分析，目前能够得到的结论：
1. sdk中只有udp会发起监听端口， 且端口随机， 在close时会正常释放。
2. 报错问题为7777端口超时，地址为127.0.0.1， 此端口和地址为阿里云服务ACM的端口7777， 在未使用ACM的情况下， 此报错对程序无影响。
3. PR#139和PR#102  可能会对此问题有一定的优化作用，但不确定是否能彻底解决。

根据 helloyxw反馈

> 我也遇到过这个问题，最后发现node项目停止时 端口号没有释放，把端口号释放了，问题就消失了。

判断应该不是nacos-sdk监听的端口（因为只有一个udp端口，且会正常释放，且端口随机），而是业务项目自身的端口。因此判断不是nacos-sdk问题或已被PR#139和PR#102优化。

因此暂时关闭issue，如仍然有问题，欢迎提交新PR并关联此PR继续讨论。
